### ISSUE TITLE
Suggestion: include / exclude namespaces

### ISSUE THREAD

**Issue by cosad3s** [raesene/eathar#21]
Thanks for this very great tool!

Is it possible to filter pss by namespace ?
Is not, it could be a good improvement :)

Typically, I would like to exclude kube-system (or any "-system")

**Comment by raesene** [comment]
Interesting, yeah that should be possible, I'll take a look at it!

**Comment by raesene** [comment]
I've added that now, you can try out the latest version with the `-e` flag which takes a set of strings, so you can exclude kube-system with `-e kube-system`
